from(db:"testdb")
  |> range(start: -5s)
  |> window(every: 1s)
  |> mean(timeSrc: "_start")
  |> window(every: inf)
  |> map(fn: (r) => {time: r._time, _measurement:r._measurement, io_time: r._value})
  |> yield(name:"0")
